// DO NOT EDIT THIS FILE
// This file is generated automatically by the typed-scss-modules library
export type Styles = {
  accent: string
  block: string
  button: string
  buttonBase: string
  error: string
  fill: string
  lg: string
  outline: string
  rounded: string
  sm: string
  text: string
  xsm: string
}

export type ClassNames = keyof Styles

declare const styles: Styles

export default styles
